name: .NET

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.410
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Run tranker
      run: dotnet run --project ./src/ComicsUpdateTracker.Mhgui      
      env:
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
    - name: Commit and push
      uses: EndBug/add-and-commit@v7
      with:
        message: 'bot: Update comic log'
